### ISSUE TITLE
Missing image sdcr.jpg

### ISSUE THREAD

**Issue by CGMossa** [data-cleaning/uRos2019_tutorial#1]
In the introduction file, there is 
```
\begin{picture}(0,0)
\put(280,-20){
\includegraphics[height=50mm]{fig/sdcr.jpg}
}
\end{picture}
```
And this file is not included in the repo. Should it be omitted altogether? 
(thanks for sharing this material!)

**Comment by markvanderloo** [comment]
Thanks, I added the figure.
